### PR TITLE
Fixes clippy lints

### PR DESCRIPTION
**Pull request by Dav1dde**
Fixes clippy lints (except tests) and adds clippy to CI

### CODE REVIEW

**Review by clux — APPROVED** [review]
looks good!

**Comment by Dav1dde** [comment]
> looks good!

That was fast :D 

Added the cache action for clippy as well, since it fetches the cargo index before running

**Comment by clux** [comment]
> cache action

Yeah, that's helpful. This repo is less professional than kube and could do with some more of this stuff :-)

**Comment by Dav1dde** [comment]
You're using the clippy action in kube:

```yaml
      - uses: actions-rs/clippy-check@v1
        with:
          args: "--workspace"
          token: ${{ secrets.GITHUB_TOKEN }}
```

Want me to change it here as well? I checked it out before but it looked like [it does not work properly for pull requests](https://github.com/actions-rs/clippy-check/issues/2), but I might be misunderstanding the issue.

Want me to change it to the action instead?

**Comment by clux** [comment]
I honestly don't remember what the token is for, but it seems to be required and the action is really nice, and we've not had any problems with it AFAIK. Getting the lints inlined into the PR makes them easy to identify when they are created.

**Comment by Dav1dde** [comment]
Updated:

```
Error: Unable to create clippy annotations! Reason: HttpError: Resource not accessible by integration
Warning: It seems that this Action is executed from the forked repository.
Warning: GitHub Actions are not allowed to create Check annotations, when executed for a forked repos. See https://github.com/actions-rs/clippy-check/issues/2 for details.
Posting clippy checks here instead.
```

Not sure what that means, but clippy is still executed, so even in the case the action fails clippy runs which is all we need.

**Comment by clux** [comment]
Ah, I guess it only work if you create a PR from a branch against kube-rs `origin`. This should work for you since you, but not many others.

**Comment by clux** [comment]
Let's try it out :-)

**Pull request merged**
